apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: test
servers: 1
agents: 2
registries: # define how registries should be created or used
  config: |
    mirrors:
      "my.company.registry":
        endpoint:
          - http://docker.m.daocloud.io:5000