apiVersion: apps/v1
kind: Deployment
metadata:
  name: samba
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: samba
  template:
    metadata:
      labels:
        app: samba
    spec:
      containers:
      - name: samba
        image: dockurr/samba:4.20.2
        env:
        - name: USER
          value: "samba"
        - name: PASS
          value: "secret"
        ports:
        - containerPort: 445
        volumeMounts:
        - name: samba-share
          mountPath: /storage
      volumes:
      - name: samba-share
        hostPath:
          path: /path/to/shared
---
apiVersion: v1
kind: Service
metadata:
  name: samba
  namespace: default
spec:
  selector:
    app: samba
  ports:
    - protocol: TCP
      port: 445
      targetPort: 445
  type: NodePort
