apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-data
  namespace: go-demo-5
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
